FROM training-lab:latest

USER root

COPY scripts/bootstrap-code-server-java.sh /usr/local/bin/before-notebook.d/20-bootstrap-code-server-java.sh

RUN chmod 0755 /usr/local/bin/before-notebook.d/20-bootstrap-code-server-java.sh

USER 1000

WORKDIR /home/jovyan/work
