apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
  - name: Training PostgreSQL
    uid: training-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: jupyterhub
    editable: true
    jsonData:
      database: jupyterhub
      postgresVersion: 1500
      sslmode: disable
      timescaledb: false
    secureJsonData:
      password: ${DB_PASSWORD}
  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
